### PR TITLE
po/pt_BR.po: add

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by Cogitri** [comment]
Thanks! Could you please follow the AngularJS commit scheme? `feat(i18n): add pt_BR lingua` or something like that?

**Comment by maxice8** [comment]
On Mon, Jan 21, 2019 at 07:36:25AM -0800, Rasmus Thomsen wrote:
> Thanks! Could you please follow the AngularJS commit scheme? `feat(i18n): add pt_BR lingua` or something like that?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cogitri/gxi/pull/15#issuecomment-456114195

added

**Comment by Cogitri** [comment]
Ah, you also have to add `pt_BR` to po/LINGUAS

**Comment by maxice8** [comment]
On Mon, Jan 21, 2019 at 08:54:24AM -0800, Rasmus Thomsen wrote:
> Ah, you also have to add `pt_BR` to po/LINGUAS
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Cogitri/gxi/pull/15#issuecomment-456138923

done

**Comment by Cogitri** [comment]
Thanks!

**Pull request merged**
